### ISSUE TITLE
Dreww__ and DanMunchie: Rule Break

### ISSUE THREAD

**Issue by DolceB** [Ruinscraft/mcatlas-wiki#1]
Simply put, Drew__ and DanMunchie who are members of the Clan_County town have been reported twice by two different people that atleast Drew__ has been responsible for pouring lava on them and killing them. spacegal and katieket both claimed Drew__ was responsible for killing them and after them two as well as myself confronted them about it, they just went on about not having evidence and saying we were ganging up on them. spacegal and katieket dont even know each other, and what would two complete strangers that have never interacted with one another gain from lying about two other strangers theyve never interacted with? They need to be reprimanded.

**Comment by ds58** [comment]
Please report this on Discord or our Forums. We do not use Github issues for user reports.
