### ISSUE TITLE
Kick from a nation for nothing.

### ISSUE THREAD

**Issue by SplatPiggy** [Ruinscraft/mcatlas-wiki#2]
Me and my friends got kicked from Terra-Australia because I sold 2 cows to a person and one died on the way and we didn't give them a new one for free. One of there friends invited my friend to there town and he took a gold pick ,he didn't know it was theirs so they got us kicked. This person was FishyMcNugget

**Comment by ds58** [comment]
Sorry, this is not the place for reporting issues on MCAtlas. Please use our discord or forums.
